const menus = [
  {
    id: 1,
    name: "Sake nigiri & Nori maki",
    image: "/image/menu01.png",
    type: "寿司",
    price: 1200,
  },
  {
    id: 2,
    name: "Salmon maki",
    image: "/image/menu02.png",
    type: "寿司",
    price: 800,
  },
  {
    id: 3,
    name: "Sashimi",
    image: "/image/menu03.png",
    type: "刺身",
    price: 1500,
  },
  {
    id: 4,
    name: "Mixed platter",
    image: "/image/menu04.png",
    type: "寿司",
    price: 2500,
  },
  {
    id: 5,
    name: "Nigiri platter",
    image: "/image/menu05.png",
    type: "寿司",
    price: 2000,
  },
  {
    id: 6,
    name: "Nigiri & Maki platter",
    image: "/image/menu06.png",
    type: "寿司",
    price: 2300,
  },
  { id: 7, name: "Maguro Nigiri", type: "寿司", price: 450 },
  { id: 8, name: "Sake Nigiri", type: "寿司", price: 400 },
  { id: 9, name: "Unagi Nigiri", type: "寿司", price: 500 },
  { id: 10, name: "Ebi Nigiri", type: "寿司", price: 350 },
  { id: 11, name: "Hamachi Nigiri", type: "寿司", price: 500 },
  { id: 12, name: "Maguro Sashimi", type: "刺身", price: 1200 },
  { id: 13, name: "Sake Sashimi", type: "刺身", price: 1100 },
  { id: 14, name: "Hamachi Sashimi", type: "刺身", price: 1300 },
  { id: 15, name: "Tako Sashimi", type: "刺身", price: 1000 },
  { id: 16, name: "Hotate Sashimi", type: "刺身", price: 1400 },
  { id: 17, name: "California Roll", type: "寿司", price: 800 },
  { id: 18, name: "Spicy Maguro Maki", type: "寿司", price: 900 },
  { id: 19, name: "Philadelphia Roll", type: "寿司", price: 900 },
  { id: 20, name: "Dragon Roll", type: "寿司", price: 1200 },
  { id: 21, name: "Rainbow Roll", type: "寿司", price: 1300 },
  { id: 22, name: "Caterpillar Roll", type: "寿司", price: 1300 },
  { id: 23, name: "Kumo Maki", type: "寿司", price: 1400 },
  { id: 24, name: "Bōkēn Maki", type: "寿司", price: 1500 },
  { id: 25, name: "Tempura Maki", type: "寿司", price: 1100 },
  { id: 26, name: "Crunchy Roll", type: "寿司", price: 1000 },
  { id: 27, name: "Edamame", type: "前菜", price: 500 },
  { id: 28, name: "Gyoza", type: "前菜", price: 600 },
  { id: 29, name: "Agedashi Tofu", type: "前菜", price: 700 },
  { id: 30, name: "Tempura Appetizer", type: "前菜", price: 800 },
  { id: 31, name: "Shumai", type: "前菜", price: 650 },
  { id: 32, name: "Tori Teriyaki", type: "その他", price: 1500 },
  { id: 33, name: "Gyu Teriyaki", type: "その他", price: 1800 },
  { id: 34, name: "Sake Teriyaki", type: "その他", price: 1700 },
  { id: 35, name: "Katsu Don", type: "丼", price: 1400 },
  { id: 36, name: "Unagi Don", type: "丼", price: 1900 },
  { id: 37, name: "Tempura Udon", type: "うどん", price: 1200 },
  { id: 38, name: "Yaki Soba", type: "そば", price: 1300 },
  { id: 39, name: "Ramen", type: "ラーメン", price: 1100 },
  { id: 40, name: "Zaru Soba", type: "そば", price: 1000 },
  { id: 41, name: "Kaisen Udon", type: "うどん", price: 1400 },
  { id: 42, name: "Ryokucha", type: "飲料", price: 250 },
  { id: 43, name: "Soft Drinks", type: "飲料", price: 200 },
  { id: 44, name: "Ramune", type: "飲料", price: 300 },
  { id: 45, name: "Iced Matcha Latte", type: "飲料", price: 450 },
  { id: 46, name: "Calpico", type: "飲料", price: 350 },
  { id: 47, name: "Sake", type: "飲料", price: 700 },
  { id: 48, name: "Asahi Beer", type: "飲料", price: 600 },
  { id: 49, name: "Sapporo Beer", type: "飲料", price: 600 },
  { id: 50, name: "Plum Wine (Umeshu)", type: "飲料", price: 800 },
  { id: 51, name: "Shochu", type: "飲料", price: 900 },
];

export default menus;
